/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as CreatorDashboardRouteImport } from './routes/creator.dashboard'
import { Route as GigsIdRouteImport } from './routes/gigs.$id'
import { Route as GigsNewRouteImport } from './routes/gigs.new'
import { Route as GigsIdEditRouteImport } from './routes/gigs.$id_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: '/creator/dashboard',
  path: '/creator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIdRoute = GigsIdRouteImport.update({
  id: '/gigs/$id',
  path: '/gigs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsNewRoute = GigsNewRouteImport.update({
  id: '/gigs/new',
  path: '/gigs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIdEditRoute = GigsIdEditRouteImport.update({
  id: '/gigs/$id_/edit',
  path: '/gigs/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-bookings': typeof MyBookingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/gigs/$id': typeof GigsIdRoute
  '/gigs/new': typeof GigsNewRoute
  '/gigs/$id/edit': typeof GigsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-bookings': typeof MyBookingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/gigs/$id': typeof GigsIdRoute
  '/gigs/new': typeof GigsNewRoute
  '/gigs/$id/edit': typeof GigsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-bookings': typeof MyBookingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/gigs/$id': typeof GigsIdRoute
  '/gigs/new': typeof GigsNewRoute
  '/gigs/$id_/edit': typeof GigsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketplace'
    | '/my-bookings'
    | '/sign-in'
    | '/sign-up'
    | '/unauthorized'
    | '/bookings/$id'
    | '/creator/dashboard'
    | '/gigs/$id'
    | '/gigs/new'
    | '/gigs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marketplace'
    | '/my-bookings'
    | '/sign-in'
    | '/sign-up'
    | '/unauthorized'
    | '/bookings/$id'
    | '/creator/dashboard'
    | '/gigs/$id'
    | '/gigs/new'
    | '/gigs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/marketplace'
    | '/my-bookings'
    | '/sign-in'
    | '/sign-up'
    | '/unauthorized'
    | '/bookings/$id'
    | '/creator/dashboard'
    | '/gigs/$id'
    | '/gigs/new'
    | '/gigs/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyBookingsRoute: typeof MyBookingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  BookingsIdRoute: typeof BookingsIdRoute
  CreatorDashboardRoute: typeof CreatorDashboardRoute
  GigsIdRoute: typeof GigsIdRoute
  GigsNewRoute: typeof GigsNewRoute
  GigsIdEditRoute: typeof GigsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/dashboard': {
      id: '/creator/dashboard'
      path: '/creator/dashboard'
      fullPath: '/creator/dashboard'
      preLoaderRoute: typeof CreatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/$id': {
      id: '/gigs/$id'
      path: '/gigs/$id'
      fullPath: '/gigs/$id'
      preLoaderRoute: typeof GigsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/new': {
      id: '/gigs/new'
      path: '/gigs/new'
      fullPath: '/gigs/new'
      preLoaderRoute: typeof GigsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/$id_/edit': {
      id: '/gigs/$id_/edit'
      path: '/gigs/$id/edit'
      fullPath: '/gigs/$id/edit'
      preLoaderRoute: typeof GigsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyBookingsRoute: MyBookingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  BookingsIdRoute: BookingsIdRoute,
  CreatorDashboardRoute: CreatorDashboardRoute,
  GigsIdRoute: GigsIdRoute,
  GigsNewRoute: GigsNewRoute,
  GigsIdEditRoute: GigsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
